# permissions for end users to view pandurangawsmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pandurangawsmanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmstate-operator-pkr
    app.kubernetes.io/part-of: vmstate-operator-pkr
    app.kubernetes.io/managed-by: kustomize
  name: pandurangawsmanager-viewer-role
rules:
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsmanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsmanagers/status
  verbs:
  - get
