# permissions for end users to view pandurangawsec2s.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pandurangawsec2-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmstate-operator-pkr
    app.kubernetes.io/part-of: vmstate-operator-pkr
    app.kubernetes.io/managed-by: kustomize
  name: pandurangawsec2-viewer-role
rules:
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsec2s
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsec2s/status
  verbs:
  - get
