---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsec2s
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsec2s/finalizers
  verbs:
  - update
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsec2s/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsmanagers/finalizers
  verbs:
  - update
- apiGroups:
  - aws.pandurang.com
  resources:
  - pandurangawsmanagers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
