//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSEC2) DeepCopyInto(out *PandurangAWSEC2) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSEC2.
func (in *PandurangAWSEC2) DeepCopy() *PandurangAWSEC2 {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSEC2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PandurangAWSEC2) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSEC2List) DeepCopyInto(out *PandurangAWSEC2List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PandurangAWSEC2, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSEC2List.
func (in *PandurangAWSEC2List) DeepCopy() *PandurangAWSEC2List {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSEC2List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PandurangAWSEC2List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSEC2Spec) DeepCopyInto(out *PandurangAWSEC2Spec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSEC2Spec.
func (in *PandurangAWSEC2Spec) DeepCopy() *PandurangAWSEC2Spec {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSEC2Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSEC2Status) DeepCopyInto(out *PandurangAWSEC2Status) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSEC2Status.
func (in *PandurangAWSEC2Status) DeepCopy() *PandurangAWSEC2Status {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSEC2Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSManager) DeepCopyInto(out *PandurangAWSManager) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSManager.
func (in *PandurangAWSManager) DeepCopy() *PandurangAWSManager {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSManager)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PandurangAWSManager) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSManagerList) DeepCopyInto(out *PandurangAWSManagerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PandurangAWSManager, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSManagerList.
func (in *PandurangAWSManagerList) DeepCopy() *PandurangAWSManagerList {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSManagerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PandurangAWSManagerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSManagerSpec) DeepCopyInto(out *PandurangAWSManagerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSManagerSpec.
func (in *PandurangAWSManagerSpec) DeepCopy() *PandurangAWSManagerSpec {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSManagerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PandurangAWSManagerStatus) DeepCopyInto(out *PandurangAWSManagerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PandurangAWSManagerStatus.
func (in *PandurangAWSManagerStatus) DeepCopy() *PandurangAWSManagerStatus {
	if in == nil {
		return nil
	}
	out := new(PandurangAWSManagerStatus)
	in.DeepCopyInto(out)
	return out
}
