apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-configmap
data:
  instance-type: t2.micro 
  image-id: ami-0d0ca2066b861631c

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: configmap-container
      image: nginx:latest
      volumeMounts:
      - name: configmap-volume
        mountPath: /opt/
  volumes:
    - name: configmap-volume
      configMap:
        name: aws-configmap